routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'FrontEnd\HomeController@index')->name('index');
Route::get('/home', 'FrontEnd\HomeController@index')->name('home');
Route::get('/search','FrontEnd\HomeController@search')->name('search');
Route::get('/aboutus','FrontEnd\HomeController@aboutus')->name('aboutus');
Route::get('/contactus','FrontEnd\HomeController@contactus')->name('contactus');
Route::get('/privacy','FrontEnd\HomeController@privacy')->name('privacy');
Route::get('/language','FrontEnd\HomeController@language')->name('language');
Route::post('/sendcontactus','FrontEnd\HomeController@sendcontactus')->name('sendcontactus');
Route::get('/set_language/{id}','FrontEnd\HomeController@set_language')->name('set_language');
Route::get('/article/view/{id}','FrontEnd\HomeController@viewArticle')->name('viewArticle');
Route::get('/book/view/{id}','FrontEnd\HomeController@viewBook')->name('viewBook');
Route::get('/book/{type?}/{id?}','FrontEnd\HomeController@book')->name('book');
Route::get('/article/{type?}/{id?}','FrontEnd\HomeController@article')->name('article');
Route::get('/comments/{type}/{id}','FrontEnd\HomeController@comments')->name('comments');
Route::get('/rating/{type}/{id}/{rating}','FrontEnd\HomeController@rating')->name('rating');
Auth::routes();



Route::group(['as' => 'admin.','prefix' => 'admin','namespace' => 'Admin','middleware' => ['auth','admin']],function(){
    //Route::get('post/updateStatus/{post}','PostController@updateStatus')->name('post.updateStatus');
    //,'middleware' => ['auth','admin']

    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::get('dashboard/ajaxSuccess/{route}/{status}/{rv?}','DashboardController@ajaxSuccess')->name('dashboard.ajaxSuccess');
    //Book
    Route::resource('book','BookController');
    Route::resource('bookCategory','BookCategoryController');
    Route::resource('author','AuthorController');

    //Article
    Route::resource('post','PostController');
    Route::resource('postCategory','PostCategoryController');


    //Extra
    Route::resource('user','UserController');
    Route::resource('tag','TagController');
    Route::resource('comment','CommentController');
    Route::resource('language','LanguageController');
    Route::resource('translator','TranslatorController');
    Route::resource('websetting','WebSettingController');
    Route::get('/book/changeStatus/{book}','BookController@ChangeStatus')->name('book.changeStatus');
    Route::get('/post/changeStatus/{post}','PostController@ChangeStatus')->name('post.changeStatus');

    /*Media Manager*/
    Route::get('/media-manager','DashboardController@mediaManager')->name('media-manager');

    /*System Setting */
    Route::resource('systemSetting','SystemSetting');

});



Route::group(['as' => 'user.','prefix' => 'user','namespace' => 'User','middleware' => ['auth']],function(){

    Route::get('profile/edit','UserController@editProfile')->name('profile.edit');
    Route::get('setting','UserController@setting')->name('setting.edit');
    Route::get('password','UserController@password')->name('password.edit');

    Route::put('profile/{id?}','UserController@updateProfile')->name('profile.update');
    Route::put('setting/{id?}','UserController@updateSetting')->name('setting.update');
    Route::put('password/{id?}','UserController@updatePassword')->name('password.update');

    Route::post('make-comment/{type}/{id}','UserController@makeComment')->name('makeComment');

});

Route::get('user/profile/{id?}','User\UserController@profile')->name('user.profile.show');

Auth::routes();

/*Media Manager*/
\TalvBansal\MediaManager\Routes\MediaRoutes::get();

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    public function tags(){
        return $this->belongsToMany('App\Tag');
    }

    public function authors(){
        return $this->belongsToMany('App\Author');
    }

    public function translators(){
        return $this->belongsToMany('App\Translator');
    }

    public function categories(){
        return $this->belongsToMany('App\Category');
    }


    public function user(){
        return $this->belongsTo('App\User');
    }

    public function comments(){
        return $this->belongsToMany('App\Comment');
    }

    public function eightComments(){
        return $this->hasMany('App\Comment')->latest()->limit(8);
    }

    public function rate(){
        return $this->hasMany('App\Rating');
    }

}

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{


    public function posts(){
        return $this->belongsToMany('App\Post');
    }

    public function books(){
        return $this->belongsToMany('App\Book');
    }
}

app/Http/Controllers/Admin/BookController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Author;
use App\Book;
use App\Category;
use App\Language;
use App\Tag;
use App\Translator;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::latest()->paginate(Config::get('websettings.adminItemPerPage'));

        return view('admin.book.book.index',compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $authors = Author::all();
        $categories = Category::all()->where('category_for','book');
        $tags = Tag::all();
        $translators = Translator::all();
        $languages = Language::all()->where('is_active',true);

        return view('admin.book.book.create',compact('authors','categories','tags','translators','languages'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

       $this->validate($request,[
           'title' => 'required',
           'description' => 'required',
           'image' => 'mimes:png,jpg,gif,jpeg,bmp',
           'language' => 'required'
       ]);

       $imagename = 'storage/book/default.png';
       $image = $request->file('image');
       $slug = str_slug($request->title);
       $dir = 'book';
       if(isset($image) && $image){

           if (!Storage::disk('public')->exists($dir)) {
               Storage::disk('public')->makeDirectory($dir);
           }
           $imagename = $dir.'/'.$slug.'-'.uniqid().'.'.$image->getClientOriginalExtension();

           $bookImage = Image::make($image)->resize(512,512)->save('temp/tmp.'.$image->getClientOriginalExtension());
           Storage::disk('public')->put($imagename,$bookImage);
           $imagename = 'storage/'.$imagename;
       }


       $book = new Book();
       $book->user_id = Auth::id();
       $book->is_active = $request->active ? true : false;
       $book->image = $imagename;
       $book->title = $request->title;
       $book->language_id = $request->language;
       $book->description = $request->description;
       $book->book_link = $request->book_link;
       $book->save();
       $book->authors()->attach($request->author);
       $book->tags()->attach($request->tag);
       $book->translators()->attach($request->translator);
       $book->categories()->attach($request->category);

       return redirect()->route('admin.book.index')->with('status','Book Successfully Added');
    }



    /**
     * Display the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(Book $book)
    {
        return view('admin.book.book.show',compact('book'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        $authors = Author::all();
        $categories = Category::all()->where('category_for','book');
        $tags = Tag::all();
        $translators = Translator::all();
        $languages = Language::all()->where('is_active',true);


        $mainBookAuthors = $book->authors;
        $mainBookTranslators = $book->translators;
        $mainBookCategories = $book->categories;
        $mainBookTags = $book->tags;

        $authorIdArray = [];
        foreach ($mainBookAuthors as $singleAuthorData){
            $authorIdArray[] = $singleAuthorData->id;
        }


        $translatorIdArray = [];
        foreach ($mainBookTranslators as $singleTranslatorData){
            $translatorIdArray[] = $singleTranslatorData->id;
        }

        $categoryIdArray = [];
        foreach ($mainBookCategories as $singleCategoryData){
            $categoryIdArray[] = $singleCategoryData->id;
        }

        $tagIdArray = [];
        foreach ($mainBookTags as $singleTagData){
            $tagIdArray[] = $singleTagData->id;
        }

        return view('admin.book.book.edit',compact('authors','book','languages','translators','tags',
            'categories','authorIdArray','translatorIdArray','categoryIdArray','tagIdArray'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        $this->validate($request,[
            'title' => 'required',
            'description' => 'required',
            'image' => 'mimes:png,gif,jpg,jpeg,bmp',
            'language' => 'required'
        ]);

        $imagename = $book->image;
        $image = $request->file('image');
        $slug = str_slug($request->title);
        $dir = 'book';

        if(isset($image) && $image){

            $exist_image = $this->rmstorage($book->image);
            if(Storage::disk('public')->exists($exist_image)){
                Storage::disk('public')->delete($exist_image);
            }

            $imagename = $dir.'/'.$slug.'-'.uniqid().'.'.$image->getClientOriginalExtension();

            $bookImage = Image::make($image)->resize(512,512)->save('temp/tmp.'.$image->getClientOriginalExtension());
            Storage::disk('public')->put($imagename,$bookImage);
            $imagename = 'storage/'.$imagename;

        }


        $book->user_id = Auth::id();
        $book->is_active = $request->active ? true : false;
        $book->image = $imagename;
        $book->title = $request->title;
        $book->language_id = $request->language;
        $book->description = $request->description;
        $book->book_link = $request->book_link;
        $book->save();
        $book->authors()->sync($request->author);
        $book->tags()->sync($request->tag);
        $book->translators()->sync($request->translator);
        $book->categories()->sync($request->category);

        return redirect()->back()->with('status','Book Successfully Edited..');
    }

    public function changeStatus(Book $book){
     $book->is_active = !$book->is_active;
     $book->save();
     return redirect()->back()->with('status','Book Status Successfully Updated..');
    }



    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        $exist_image = $this->rmstorage($book->image);
        if(Storage::disk('public')->exists($exist_image)){
            Storage::disk('public')->delete($exist_image);
        }

        $book->tags()->detach();
        $book->authors()->detach();
        $book->translators()->detach();
        $book->categories()->detach();
        $book->delete();

        return redirect()->route('admin.book.index')->with('status','Book Successfully deleted..');
    }

    public function rmstorage($storage){
        return str_replace('storage/','',$storage);
    }

}

resources/views/admin/book/category/create.blade.php
@extends('layouts.admin.app')

@section('title','Book/Category/Create')

@push('css')


@endpush


@section('content')
    <div class="bg-white">
        <form method="post" action="{{route('admin.bookCategory.store')}}" enctype="multipart/form-data">
            @csrf
            @method('POST')
            <div class="form-group col-sm-8">
                <label for="title" class="font-weight-bold">Title</label>
                <input type="text" class="form-control" name="title">
            </div>

            <div class="form-group col-sm-8">
                <label for="image" class="font-weight-bold">Image</label>
                <input type="file" class="form-control-file" name="image">
            </div>

            <div class="form-group col-sm-8">
                <a href="{{route('admin.bookCategory.index')}}" class="btn btn-primary btn-danger">BACK</a> <input class="btn btn-primary" type="submit" value="ADD">
            </div>
            <br>

        </form>
    </div>


@endsection


@push('script')

@endpush

resources/views/admin/book/category/edit.blade.php
@extends('layouts.admin.app')

@section('title','Book/Category/Edit')

@push('css')


@endpush


@section('content')


    <div class="bg-white">
        <form method="post" action="{{route('admin.bookCategory.update',$bookCategory->id)}}" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group col-sm-8">
                <label for="title" class="font-weight-bold">Title</label>
                <input type="text" class="form-control" name="title" value="{{$bookCategory->title}}">
            </div>

            <div class="form-group col-sm-8">
                <label for="image" class="font-weight-bold">Image</label>
                <div><img src="{{asset('storage/category/'.$bookCategory->image)}}" alt="" width="60"></div>
                <input type="file" class="form-control-file" name="image">
            </div>

            <div class="form-group col-sm-8">
                <a href="{{route('admin.bookCategory.index')}}" class="btn btn-primary btn-danger">BACK</a> <input class="btn btn-primary" type="submit" value="EDIT">
            </div>
            <br>

        </form>
    </div>


@endsection


@push('script')

@endpush

resources/views/admin/book/category/index.blade.php
@extends('layouts.admin.app')

@section('title','Book/Category')

@push('css')


@endpush


@section('content')
    <a href="{{route('admin.bookCategory.create')}}" class="btn btn-primary">Add New</a>
    <br><br/>

    @if($categories->count())
        <table class="table bg-white">
            <thead>
            <tr>
                <th col="col">Image</th>
                <th scope="col">Title</th>
                <th scope="col">Posts</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($categories as $category)
                <tr>
                    <td><img src="{{asset('storage/category/'.$category->image)}}" width="70" alt=""></td>
                    <th>{{$category->title}}</th>
                    <td>{{$category->books->count()}}</td>
                    <td><a href="{{route('admin.bookCategory.edit',$category->id)}}"><i class="font-weight-bold cui-note"></i></a><a href="javascript:void(0)" class="delete-item" data-src="{{$category->id}}"><i class="font-weight-bold cui-delete"></i></a> </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="text-center">
            {{$categories->links()}}
        </div>
    @else
        <div class="bg-white text-center font-weight-bold"><br/>No Data available<br/><br></div>


    @endif
@endsection


@push('script')
    <script>
        $(".delete-item").click(function () {

            let deleteForm = document.createElement('form'),
                currentURL = `{{route('admin.bookCategory.destroy','deleteid')}}`,
                deleteURL = currentURL.replace('deleteid',this.dataset.src),
                csrfInput = document.createElement('input'),
                methodInput = document.createElement('input')
            deleteForm.style.display = 'none';
            deleteForm.method = 'POST'
            deleteForm.action = deleteURL
            csrfInput.name = `_token`
            csrfInput.value = `{{csrf_token()}}`
            methodInput.name = `_method`
            methodInput.value = `DELETE`
            deleteForm.appendChild(csrfInput)
            deleteForm.appendChild(methodInput)
            document.body.appendChild(deleteForm)
            deleteForm.submit()
        })
    </script>
@endpush