routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'FrontEnd\HomeController@index')->name('index');
Route::get('/home', 'FrontEnd\HomeController@index')->name('home');
Route::get('/search','FrontEnd\HomeController@search')->name('search');
Route::get('/aboutus','FrontEnd\HomeController@aboutus')->name('aboutus');
Route::get('/contactus','FrontEnd\HomeController@contactus')->name('contactus');
Route::get('/privacy','FrontEnd\HomeController@privacy')->name('privacy');
Route::get('/language','FrontEnd\HomeController@language')->name('language');
Route::post('/sendcontactus','FrontEnd\HomeController@sendcontactus')->name('sendcontactus');
Route::get('/set_language/{id}','FrontEnd\HomeController@set_language')->name('set_language');
Route::get('/article/view/{id}','FrontEnd\HomeController@viewArticle')->name('viewArticle');
Route::get('/book/view/{id}','FrontEnd\HomeController@viewBook')->name('viewBook');
Route::get('/book/{type?}/{id?}','FrontEnd\HomeController@book')->name('book');
Route::get('/article/{type?}/{id?}','FrontEnd\HomeController@article')->name('article');
Route::get('/comments/{type}/{id}','FrontEnd\HomeController@comments')->name('comments');
Route::get('/rating/{type}/{id}/{rating}','FrontEnd\HomeController@rating')->name('rating');
Auth::routes();



Route::group(['as' => 'admin.','prefix' => 'admin','namespace' => 'Admin','middleware' => ['auth','admin']],function(){
    //Route::get('post/updateStatus/{post}','PostController@updateStatus')->name('post.updateStatus');
    //,'middleware' => ['auth','admin']

    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::get('dashboard/ajaxSuccess/{route}/{status}/{rv?}','DashboardController@ajaxSuccess')->name('dashboard.ajaxSuccess');
    //Book
    Route::resource('book','BookController');
    Route::resource('bookCategory','BookCategoryController');
    Route::resource('author','AuthorController');

    //Article
    Route::resource('post','PostController');
    Route::resource('postCategory','PostCategoryController');


    //Extra
    Route::resource('user','UserController');
    Route::resource('tag','TagController');
    Route::resource('comment','CommentController');
    Route::resource('language','LanguageController');
    Route::resource('translator','TranslatorController');
    Route::resource('websetting','WebSettingController');
    Route::get('/book/changeStatus/{book}','BookController@ChangeStatus')->name('book.changeStatus');
    Route::get('/post/changeStatus/{post}','PostController@ChangeStatus')->name('post.changeStatus');

    /*Media Manager*/
    Route::get('/media-manager','DashboardController@mediaManager')->name('media-manager');

    /*System Setting */
    Route::resource('systemSetting','SystemSetting');

});



Route::group(['as' => 'user.','prefix' => 'user','namespace' => 'User','middleware' => ['auth']],function(){

    Route::get('profile/edit','UserController@editProfile')->name('profile.edit');
    Route::get('setting','UserController@setting')->name('setting.edit');
    Route::get('password','UserController@password')->name('password.edit');

    Route::put('profile/{id?}','UserController@updateProfile')->name('profile.update');
    Route::put('setting/{id?}','UserController@updateSetting')->name('setting.update');
    Route::put('password/{id?}','UserController@updatePassword')->name('password.update');

    Route::post('make-comment/{type}/{id}','UserController@makeComment')->name('makeComment');

});

Route::get('user/profile/{id?}','User\UserController@profile')->name('user.profile.show');

Auth::routes();

/*Media Manager*/
\TalvBansal\MediaManager\Routes\MediaRoutes::get();

app/Author.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Author extends Model
{


   public function books(){
       return $this->belongsToMany('App\Book');
   }

   public function posts(){
       return $this->belongsToMany('App\Post');
   }
}

app/Http/Controllers/Admin/AuthorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Author;
use function GuzzleHttp\Psr7\str;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class AuthorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $authors = Author::latest()->paginate(Config::get('websettings.adminItemPerPage'));
        return view('admin.author.index',compact('authors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.author.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title' => 'required',
            'image' => 'mimes:bmp,png,jpg,jpeg,gif'
        ]);

        $title = $request->title;
        $slug = str_slug($title);
        $image = $request->file('image');
        $is_active = true;

        if(isset($image) && $image){

            if (!Storage::disk('public')->exists('author')) {
                Storage::disk('public')->makeDirectory('author');
            }
            $imageName = $slug.'-'.uniqid().'.'.$image->getClientOriginalExtension();

            $tagImage = Image::make($image)->resize(500,333)->save('temp/tmp.'.$image->getClientOriginalExtension());
            Storage::disk('public')->put('author/'.$imageName,$tagImage);


        }else{
            $imageName = 'default.png';
        }

        $author = new Author();
        $author->title = $title;
        $author->slug = $slug;
        $author->is_active = $is_active;
        $author->image = $imageName;
        $author->save();
        return redirect()->back()->with('status','New Author Successfully Added.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function show(Author $author)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function edit(Author $author)
    {
        return view('admin.author.edit',compact('author'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Author $author)
    {
        $this->validate($request,[
            'title' => 'required',
            'image' => 'mimes:bmp,png,jpg,jpeg,gif'
        ]);

        $title = $request->title;
        $slug = str_slug($title);
        $image = $request->file('image');
        $is_active = true;

        if(isset($image) && $image){


            if(Storage::disk('public')->exists('author/'.$author->image)){
                Storage::disk('public')->delete('author/'.$author->image);
            }


            if (!Storage::disk('public')->exists('author')) {
                Storage::disk('public')->makeDirectory('author');
            }
            $imageName = $slug.'-'.uniqid().'.'.$image->getClientOriginalExtension();

            $tagImage = Image::make($image)->resize(500,333)->save('temp/tmp.'.$image->getClientOriginalExtension());
            Storage::disk('public')->put('author/'.$imageName,$tagImage);


        }else{
            $imageName = 'default.png';
        }

        $author->title = $title;
        $author->slug = $slug;
        $author->is_active = $is_active;
        $author->image = $imageName;
        $author->save();
        return redirect()->back()->with('status','Author Successfully Edited.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function destroy(Author $author)
    {

        if(Storage::disk('public')->exists('author/'.$author->image)){
            Storage::disk('public')->delete('author/'.$author->image);
        }
        $author->delete();
        return redirect()->back()->with('status','Author Successfully Deleted.');

    }
}

resources/views/admin/author/create.blade.php
@extends('layouts.admin.app')

@section('title','Author/Create')

@push('css')


@endpush


@section('content')

    <div class="bg-white">
        <form method="post" action="{{route('admin.author.store')}}" enctype="multipart/form-data">
            @csrf
            @method('POST')
            <div class="form-group col-sm-8">
                <label for="title" class="font-weight-bold">Title</label>
                <input type="text" class="form-control" name="title">
            </div>

            <div class="form-group col-sm-8">
                <label for="image" class="font-weight-bold">Image</label>
                <input type="file" class="form-control-file" name="image">
            </div>

            <div class="form-group col-sm-8">
                <a href="{{route('admin.author.index')}}" class="btn btn-primary btn-danger">BACK</a> <input class="btn btn-primary" type="submit" value="ADD">
            </div>
            <br>

        </form>
    </div>

@endsection


@push('script')

@endpush

resources/views/admin/author/edit.blade.php
@extends('layouts.admin.app')

@section('title','Author/Edit')

@push('css')


@endpush


@section('content')

    <div class="bg-white">
        <form method="post" action="{{route('admin.author.update',$author->id)}}" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group col-sm-8">
                <label for="title" class="font-weight-bold">Title</label>
                <input type="text" class="form-control" name="title" value="{{$author->title}}">
            </div>

            <div class="form-group col-sm-8">
                <label for="image" class="font-weight-bold">Image</label>
                <div><img src="{{asset('storage/author/'.$author->image)}}" alt="" width="60"></div>
                <input type="file" class="form-control-file" name="image">
            </div>

            <div class="form-group col-sm-8">
                <a href="{{route('admin.author.index')}}" class="btn btn-primary btn-danger">BACK</a> <input class="btn btn-primary" type="submit" value="ADD">
            </div>
            <br>

        </form>
    </div>

@endsection


@push('script')

@endpush

resources/views/admin/author/index.blade.php
@extends('layouts.admin.app')

@section('title','Author')

@push('css')

@endpush


@section('content')
    <a href="{{route('admin.author.create')}}" class="btn btn-primary">Add New</a>
    <br><br/>
    @if($authors->count())
        <table class="table bg-white">

            <thead>
            <tr>
                <th scope="col">Image</th>
                <th scope="col">Title</th>
                <th scope="col">Books</th>
                <th scope="col">Posts</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($authors as $author)
                <tr>
                    <th><img src="{{asset('storage/author/'.$author->image)}}" width="70" alt=""></th>
                    <th>{{$author->title}}</th>
                    <td>{{$author->books->count()}}</td>
                    <td>{{$author->posts->count()}}</td>
                    <td> <a href="{{route('admin.author.edit',$author->id)}}"><i class="font-weight-bold cui-note"></i></a><a href="javascript:void(0)" class="delete-item" data-src="{{$author->id}}"><i class="font-weight-bold cui-delete"></i></a></td>
                </tr>
            @endforeach
            </tbody>

        </table>

        <div class="text-center">
            {{$authors->links()}}
        </div>

    @else
        <div class="bg-white text-center font-weight-bold"><br/>No Data available<br/><br></div>

    @endif


@endsection


@push('script')
    <script>
        $(".delete-item").click(function () {

            let deleteForm = document.createElement('form'),
                currentURL = `{{route('admin.author.destroy','deleteid')}}`,
                deleteURL = currentURL.replace('deleteid',this.dataset.src),
                csrfInput = document.createElement('input'),
                methodInput = document.createElement('input')
            deleteForm.style.display = 'none';
            deleteForm.method = 'POST'
            deleteForm.action = deleteURL
            csrfInput.name = `_token`
            csrfInput.value = `{{csrf_token()}}`
            methodInput.name = `_method`
            methodInput.value = `DELETE`
            deleteForm.appendChild(csrfInput)
            deleteForm.appendChild(methodInput)
            document.body.appendChild(deleteForm)
            deleteForm.submit()
        })
    </script>
@endpush