routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'FrontEnd\HomeController@index')->name('index');
Route::get('/home', 'FrontEnd\HomeController@index')->name('home');
Route::get('/search','FrontEnd\HomeController@search')->name('search');
Route::get('/aboutus','FrontEnd\HomeController@aboutus')->name('aboutus');
Route::get('/contactus','FrontEnd\HomeController@contactus')->name('contactus');
Route::get('/privacy','FrontEnd\HomeController@privacy')->name('privacy');
Route::get('/language','FrontEnd\HomeController@language')->name('language');
Route::post('/sendcontactus','FrontEnd\HomeController@sendcontactus')->name('sendcontactus');
Route::get('/set_language/{id}','FrontEnd\HomeController@set_language')->name('set_language');
Route::get('/article/view/{id}','FrontEnd\HomeController@viewArticle')->name('viewArticle');
Route::get('/book/view/{id}','FrontEnd\HomeController@viewBook')->name('viewBook');
Route::get('/book/{type?}/{id?}','FrontEnd\HomeController@book')->name('book');
Route::get('/article/{type?}/{id?}','FrontEnd\HomeController@article')->name('article');
Route::get('/comments/{type}/{id}','FrontEnd\HomeController@comments')->name('comments');
Route::get('/rating/{type}/{id}/{rating}','FrontEnd\HomeController@rating')->name('rating');
Auth::routes();



Route::group(['as' => 'admin.','prefix' => 'admin','namespace' => 'Admin','middleware' => ['auth','admin']],function(){
    //Route::get('post/updateStatus/{post}','PostController@updateStatus')->name('post.updateStatus');
    //,'middleware' => ['auth','admin']

    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::get('dashboard/ajaxSuccess/{route}/{status}/{rv?}','DashboardController@ajaxSuccess')->name('dashboard.ajaxSuccess');
    //Book
    Route::resource('book','BookController');
    Route::resource('bookCategory','BookCategoryController');
    Route::resource('author','AuthorController');

    //Article
    Route::resource('post','PostController');
    Route::resource('postCategory','PostCategoryController');


    //Extra
    Route::resource('user','UserController');
    Route::resource('tag','TagController');
    Route::resource('comment','CommentController');
    Route::resource('language','LanguageController');
    Route::resource('translator','TranslatorController');
    Route::resource('websetting','WebSettingController');
    Route::get('/book/changeStatus/{book}','BookController@ChangeStatus')->name('book.changeStatus');
    Route::get('/post/changeStatus/{post}','PostController@ChangeStatus')->name('post.changeStatus');

    /*Media Manager*/
    Route::get('/media-manager','DashboardController@mediaManager')->name('media-manager');

    /*System Setting */
    Route::resource('systemSetting','SystemSetting');

});



Route::group(['as' => 'user.','prefix' => 'user','namespace' => 'User','middleware' => ['auth']],function(){

    Route::get('profile/edit','UserController@editProfile')->name('profile.edit');
    Route::get('setting','UserController@setting')->name('setting.edit');
    Route::get('password','UserController@password')->name('password.edit');

    Route::put('profile/{id?}','UserController@updateProfile')->name('profile.update');
    Route::put('setting/{id?}','UserController@updateSetting')->name('setting.update');
    Route::put('password/{id?}','UserController@updatePassword')->name('password.update');

    Route::post('make-comment/{type}/{id}','UserController@makeComment')->name('makeComment');

});

Route::get('user/profile/{id?}','User\UserController@profile')->name('user.profile.show');

Auth::routes();

/*Media Manager*/
\TalvBansal\MediaManager\Routes\MediaRoutes::get();

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{


    public function books(){
        return $this->belongsToMany('App\Book');
    }

    public function posts(){
        return $this->belongsToMany('App\Post');
    }

}

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Tag;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::latest()->paginate(Config::get('websettings.adminItemPerPage'));

        return view('admin.tag.index',compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tag.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request,[
          'title' => 'required|max:30',
          'image' => 'mimes:bmp,png,jpg,jpeg,gif'
      ]);


        $title = $request->title;
        $slug = str_slug($title);
        $image = $request->file('image');

        if(isset($image) && $image){
            if (!Storage::disk('public')->exists('tag')) {
                Storage::disk('public')->makeDirectory('tag');
            }
            $imageName = $slug.'-'.uniqid().'.'.$image->getClientOriginalExtension();

            $tagImage = Image::make($image)->resize(500,333)->save('temp/tmp.'.$image->getClientOriginalExtension());
            Storage::disk('public')->put('tag/'.$imageName,$tagImage);


        }else{
            $imageName = 'default.png';
        }


      $tag = new Tag();
      $tag->title = $request->title;
      $tag->slug = str_slug($request->title);
      $tag->is_active = true;
      $tag->image = $imageName;
      $tag->save();
      return redirect()->back()->with('status','Tag Successfully Added.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('admin.tag.edit',compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tag $tag)
    {
        $this->validate($request,[
            'title' => 'required|max:30',
            'image' => 'mimes:bmp,png,jpg,jpeg,gif'
        ]);


        $title = $request->title;
        $slug = str_slug($title);
        $image = $request->file('image');

        if(isset($image) && $image){


            if(Storage::disk('public')->exists('tag/'.$tag->image)){
                Storage::disk('public')->delete('tag/'.$tag->image);
            }


            if (!Storage::disk('public')->exists('tag')) {
                Storage::disk('public')->makeDirectory('tag');
            }
            $imageName = $slug.'-'.uniqid().'.'.$image->getClientOriginalExtension();

            $tagImage = Image::make($image)->resize(500,333)->save('temp/tmp.'.$image->getClientOriginalExtension());
            Storage::disk('public')->put('tag/'.$imageName,$tagImage);


        }else{
            $imageName = 'default.png';
        }


        $tag->title = $title;
        $tag->slug = $slug;
        $tag->is_active = true;
        $tag->image = $imageName;
        $tag->save();
        return redirect()->back()->with('status','Tag Successfully Updated..');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {

        if(Storage::disk('public')->exists('tag/'.$tag->image)){
            Storage::disk('public')->delete('tag/'.$tag->image);
        }

        $tag->delete();
        return redirect()->back()->with('status','Tag Successfully Deleted.');
    }
}

resources/views/admin/tag/create.blade.php
@extends('layouts.admin.app')

@section('title','Tag/Create')

@push('css')


@endpush


@section('content')
<div class="bg-white">
    <form method="post" action="{{route('admin.tag.store')}}" enctype="multipart/form-data">
        @csrf
        @method('POST')
        <div class="form-group col-sm-8">
            <label for="title" class="font-weight-bold">Title</label>
            <input type="text" class="form-control" name="title">
        </div>

        <div class="form-group col-sm-8">
            <label for="image" class="font-weight-bold">Image</label>
            <input type="file" class="form-control-file" name="image">
        </div>

        <div class="form-group col-sm-8">
            <a href="{{route('admin.tag.index')}}" class="btn btn-primary btn-danger">BACK</a> <input class="btn btn-primary" type="submit" value="ADD">
        </div>
        <br>

    </form>
</div>

@endsection


@push('script')

@endpush

resources/views/admin/tag/edit.blade.php
@extends('layouts.admin.app')

@section('title','Tag/Edit')

@push('css')


@endpush


@section('content')

    <div class="bg-white">
        <form method="post" action="{{route('admin.tag.update',$tag->id)}}" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group col-sm-8">
                <label for="title" class="font-weight-bold">Title</label>
                <input type="text" class="form-control" name="title" value="{{$tag->title}}">
            </div>

            <div class="form-group col-sm-8">
                <label for="image" class="font-weight-bold">Image</label>
                <div><img src="{{asset('storage/tag/'.$tag->image)}}" alt="" width="60"></div>
                <input type="file" class="form-control-file" name="image">
            </div>


            <div class="form-group col-sm-8">
                <a href="{{route('admin.tag.index')}}" class="btn btn-primary btn-danger">BACK</a> <input class="btn btn-primary" type="submit" value="EDIT">
            </div>
            <br>

        </form>
    </div>


@endsection


@push('script')

@endpush

resources/views/admin/tag/index.blade.php
@extends('layouts.admin.app')

@section('title','Tag')

@push('css')
    <style>
        .table{
            background: #fff;
        }
    </style>

@endpush


@section('content')

    <a href="{{route('admin.tag.create')}}" class="btn btn-primary">Add New</a>
    <br><br/>

    @if($tags->count())

    <table class="table">

            <thead>
        <tr>
            <th scope="col">Image</th>
            <th scope="col">Title</th>
            <th scope="col">Books</th>
            <th scope="col">Posts</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
            @foreach($tags as $tag)
                <tr>
            <td><img src="{{asset('storage/tag/'.$tag->image)}}" width="70" alt=""></td>
            <td>{{$tag->title}}</td>
            <td>{{$tag->books->count()}}</td>
            <td>{{$tag->posts->count()}}</td>
            <td><a href="{{route('admin.tag.edit',$tag->id)}}"><i class="font-weight-bold cui-note"></i></a><a href="javascript:void(0)" class="delete-item" data-src="{{$tag->id}}"><i class="font-weight-bold cui-delete"></i></a> </td>
                </tr>
                @endforeach
        </tbody>

    </table>

    <div class="text-center">
        {{$tags->links()}}
    </div>
    @else
        <div class="bg-white text-center font-weight-bold"><br/>No Data available<br/><br></div>
    @endif

@endsection


@push('script')
<script>
    $(".delete-item").click(function () {

        let deleteForm = document.createElement('form'),
            currentURL = `{{route('admin.tag.destroy','deleteid')}}`,
            deleteURL = currentURL.replace('deleteid',this.dataset.src),
            csrfInput = document.createElement('input'),
            methodInput = document.createElement('input')
        deleteForm.style.display = 'none';
        deleteForm.method = 'POST'
        deleteForm.action = deleteURL
        csrfInput.name = `_token`
        csrfInput.value = `{{csrf_token()}}`
        methodInput.name = `_method`
        methodInput.value = `DELETE`
        deleteForm.appendChild(csrfInput)
        deleteForm.appendChild(methodInput)
        document.body.appendChild(deleteForm)
        deleteForm.submit()
    })
</script>
@endpush