routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'FrontEnd\HomeController@index')->name('index');
Route::get('/home', 'FrontEnd\HomeController@index')->name('home');
Route::get('/search','FrontEnd\HomeController@search')->name('search');
Route::get('/aboutus','FrontEnd\HomeController@aboutus')->name('aboutus');
Route::get('/contactus','FrontEnd\HomeController@contactus')->name('contactus');
Route::get('/privacy','FrontEnd\HomeController@privacy')->name('privacy');
Route::get('/language','FrontEnd\HomeController@language')->name('language');
Route::post('/sendcontactus','FrontEnd\HomeController@sendcontactus')->name('sendcontactus');
Route::get('/set_language/{id}','FrontEnd\HomeController@set_language')->name('set_language');
Route::get('/article/view/{id}','FrontEnd\HomeController@viewArticle')->name('viewArticle');
Route::get('/book/view/{id}','FrontEnd\HomeController@viewBook')->name('viewBook');
Route::get('/book/{type?}/{id?}','FrontEnd\HomeController@book')->name('book');
Route::get('/article/{type?}/{id?}','FrontEnd\HomeController@article')->name('article');
Route::get('/comments/{type}/{id}','FrontEnd\HomeController@comments')->name('comments');
Route::get('/rating/{type}/{id}/{rating}','FrontEnd\HomeController@rating')->name('rating');
Auth::routes();



Route::group(['as' => 'admin.','prefix' => 'admin','namespace' => 'Admin','middleware' => ['auth','admin']],function(){
    //Route::get('post/updateStatus/{post}','PostController@updateStatus')->name('post.updateStatus');
    //,'middleware' => ['auth','admin']

    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::get('dashboard/ajaxSuccess/{route}/{status}/{rv?}','DashboardController@ajaxSuccess')->name('dashboard.ajaxSuccess');
    //Book
    Route::resource('book','BookController');
    Route::resource('bookCategory','BookCategoryController');
    Route::resource('author','AuthorController');

    //Article
    Route::resource('post','PostController');
    Route::resource('postCategory','PostCategoryController');


    //Extra
    Route::resource('user','UserController');
    Route::resource('tag','TagController');
    Route::resource('comment','CommentController');
    Route::resource('language','LanguageController');
    Route::resource('translator','TranslatorController');
    Route::resource('websetting','WebSettingController');
    Route::get('/book/changeStatus/{book}','BookController@ChangeStatus')->name('book.changeStatus');
    Route::get('/post/changeStatus/{post}','PostController@ChangeStatus')->name('post.changeStatus');

    /*Media Manager*/
    Route::get('/media-manager','DashboardController@mediaManager')->name('media-manager');

    /*System Setting */
    Route::resource('systemSetting','SystemSetting');

});



Route::group(['as' => 'user.','prefix' => 'user','namespace' => 'User','middleware' => ['auth']],function(){

    Route::get('profile/edit','UserController@editProfile')->name('profile.edit');
    Route::get('setting','UserController@setting')->name('setting.edit');
    Route::get('password','UserController@password')->name('password.edit');

    Route::put('profile/{id?}','UserController@updateProfile')->name('profile.update');
    Route::put('setting/{id?}','UserController@updateSetting')->name('setting.update');
    Route::put('password/{id?}','UserController@updatePassword')->name('password.update');

    Route::post('make-comment/{type}/{id}','UserController@makeComment')->name('makeComment');

});

Route::get('user/profile/{id?}','User\UserController@profile')->name('user.profile.show');

Auth::routes();

/*Media Manager*/
\TalvBansal\MediaManager\Routes\MediaRoutes::get();

resources/views/admin/main/dashboard.blade.php
@extends('layouts.admin.app')

@section('title','Dashboard')

@push('css')


@endpush


@section('content')
    <div class="row">
        <div class="col-sm-6 col-lg-3">
            <div class="card text-white bg-primary">
                <div class="card-body pb-0">

                    <div class="text-value">{{array_sum($postArr)}}</div>
                    <div>Articles</div>
                </div>
                <div class="chart-wrapper mt-3 mx-3" style="height:70px;">
                    <canvas class="chart" id="card-chart1" height="70"></canvas>
                </div>
            </div>
        </div>
        <!-- /.col-->
        <div class="col-sm-6 col-lg-3">
            <div class="card text-white bg-info">
                <div class="card-body pb-0">

                    <div class="text-value">{{array_sum($bookArr)}}</div>
                    <div>Books</div>
                </div>
                <div class="chart-wrapper mt-3 mx-3" style="height:70px;">
                    <canvas class="chart" id="card-chart2" height="70"></canvas>
                </div>
            </div>
        </div>
        <!-- /.col-->
        <div class="col-sm-6 col-lg-3">
            <div class="card text-white bg-warning">
                <div class="card-body pb-0">

                    <div class="text-value">{{array_sum($userArr)}}</div>
                    <div>Users</div>
                </div>
                <div class="chart-wrapper mt-3" style="height:70px;">
                    <canvas class="chart" id="card-chart3" height="70"></canvas>
                </div>
            </div>
        </div>
        <!-- /.col-->
        <div class="col-sm-6 col-lg-3">
            <div class="card text-white bg-danger">
                <div class="card-body pb-0">
                    <div class="btn-group float-right">

                    </div>
                    <div class="text-value">{{array_sum($commentArr)}}</div>
                    <div>Comments</div>
                </div>
                <div class="chart-wrapper mt-3 mx-3" style="height:70px;">
                    <canvas class="chart" id="card-chart4" height="70"></canvas>
                </div>
            </div>
        </div>
        <!-- /.col-->
    </div>
@endsection


@push('script')
    <!-- Plugins and scripts required by this view-->
    <script src="{{asset('assets/admin/node_modules/chart.js/dist/Chart.min.js')}}"></script>
    <script src="{{asset('assets/admin/node_modules/@coreui/coreui-plugin-chartjs-custom-tooltips/dist/js/custom-tooltips.min.js')}}"></script>
    <script>

        /* eslint-disable no-magic-numbers */
        // Disable the on-canvas tooltip
        Chart.defaults.global.pointHitDetectionRadius = 1;
        Chart.defaults.global.tooltips.enabled = false;
        Chart.defaults.global.tooltips.mode = 'index';
        Chart.defaults.global.tooltips.position = 'nearest';
        Chart.defaults.global.tooltips.custom = CustomTooltips; // eslint-disable-next-line no-unused-vars

        var d1 = <?php echo json_encode($postArr); ?>;
        var cardChart1 = new Chart($('#card-chart1'), {
            type: 'line',
            data: {
                labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                datasets: [{
                    label: 'Articles',
                    backgroundColor: getStyle('--primary'),
                    borderColor: 'rgba(255,255,255,.55)',
                    data: [d1[1],d1[2] ,d1[3] ,d1[4] ,d1[5] ,d1[6] ,d1[7], d1[8], d1[9], d1[10], d1[11],d1[12]]
                }]
            },
            options: {
                maintainAspectRatio: false,
                legend: {
                    display: false
                },
                scales: {
                    xAxes: [{
                        gridLines: {
                            color: 'transparent',
                            zeroLineColor: 'transparent'
                        },
                        ticks: {
                            fontSize: 2,
                            fontColor: 'transparent'
                        }
                    }],
                    yAxes: [{
                        display: false,
                        ticks: {
                            display: true,
                            min: 0,
                            max: 84
                        }
                    }]
                },
                elements: {
                    line: {
                        borderWidth: 1
                    },
                    point: {
                        radius: 3,
                        hitRadius: 10,
                        hoverRadius: 4
                    }
                }
            }
        }); // eslint-disable-next-line no-unused-vars

        var d2 = <?php echo json_encode($bookArr); ?>;
        var cardChart2 = new Chart($('#card-chart2'), {
            type: 'line',
            data: {
                labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                datasets: [{
                    label: 'Books',
                    backgroundColor: getStyle('--info'),
                    borderColor: 'rgba(255,255,255,.55)',
                    data: [d2[1],d2[2] ,d2[3] ,d2[4] ,d2[5] ,d2[6] ,d2[7] , d2[8], d2[9], d2[10], d2[11],d2[12]]
                }]
            },
            options: {
                maintainAspectRatio: false,
                legend: {
                    display: false
                },
                scales: {
                    xAxes: [{
                        gridLines: {
                            color: 'transparent',
                            zeroLineColor: 'transparent'
                        },
                        ticks: {
                            fontSize: 2,
                            fontColor: 'transparent'
                        }
                    }],
                    yAxes: [{
                        display: false,
                        ticks: {
                            display: false,
                            min: 0,
                            max: 84
                        }
                    }]
                },
                elements: {
                    line: {
                        tension: 0.00001,
                        borderWidth: 1
                    },
                    point: {
                        radius: 3,
                        hitRadius: 10,
                        hoverRadius: 4
                    }
                }
            }
        }); // eslint-disable-next-line no-unused-vars
        var d3 = <?php echo json_encode($userArr); ?>;
        var cardChart3 = new Chart($('#card-chart3'), {
            type: 'line',
            data: {
                labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                datasets: [{
                    label: 'User Registered',
                    backgroundColor: 'rgba(255,255,255,.2)',
                    borderColor: 'rgba(255,255,255,.55)',
                    data: [d3[1],d3[2] ,d3[3] ,d3[4] ,d3[5] ,d3[6] ,d3[7] , d3[8], d3[9], d3[10], d3[11],d3[12]]
                }]
            },
            options: {
                maintainAspectRatio: false,
                legend: {
                    display: false
                },
                scales: {
                    xAxes: [{
                        display: false
                    }],
                    yAxes: [{
                        display: false
                    }]
                },
                elements: {
                    line: {
                        borderWidth: 2
                    },
                    point: {
                        radius: 0,
                        hitRadius: 10,
                        hoverRadius: 4
                    }
                }
            }
        }); // eslint-disable-next-line no-unused-vars
       var d4 = <?php echo json_encode($commentArr); ?>;
        var cardChart4 = new Chart($('#card-chart4'), {
            type: 'bar',
            data: {
                labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                datasets: [{
                    label: 'Comments',
                    backgroundColor: 'rgba(255,255,255,.2)',
                    borderColor: 'rgba(255,255,255,.55)',
                    data: [d4[1],d4[2] ,d4[3] ,d4[4] ,d4[5] ,d4[6] ,d4[7] , d4[8], d4[9], d4[10], d4[11],d4[12]]
                }]
            },
            options: {
                maintainAspectRatio: false,
                legend: {
                    display: false
                },
                scales: {
                    xAxes: [{
                        display: false,
                        barPercentage: 0.6
                    }],
                    yAxes: [{
                        display: false
                    }]
                }
            }
        }); // eslint-disable-next-line no-unused-vars


        //# sourceMappingURL=main.js.map
    </script>
@endpush

resources/views/admin/main/setting.blade.php
@extends('layouts.admin.app')

@section('title','Settings')

@push('css')


@endpush


@section('content')

    <div class="bg-white">
        <a href="{{route('admin.systemSetting.index')}}" class="btn btn-primary btn-success">More Settings</a>
        <form method="post" action="{{route('admin.websetting.store')}}" enctype="multipart/form-data">
            @csrf
            @method('POST')


            <div class="form-group col-sm-8">
                <label for="title" class="font-weight-bold">Site Title</label>
                <input type="text" class="form-control" name="siteTitle" value="{{Config::get('websettings.siteTitle')}}">
            </div>


            <div class="form-group col-sm-8">
                <label for="title" class="font-weight-bold">Homepage Title</label>
                <input type="text" class="form-control" name="homePageTitle" value="{{Config::get('websettings.homePageTitle')}}">
            </div>

            <div class="form-group col-sm-8">
                <label for="title" class="font-weight-bold">Default Language</label>
                <select name="defaultLanguage" class="form-control">
                    @foreach($languages as $language)
                        <option value="{{$language->id}}"
                        {{Config::get('websettings.defaultLanguage') == $language->id ? 'selected' : ''}}>{{$language->language}}</option>
                        @endforeach
                </select>
            </div>

            <div class="form-group col-sm-8">
                <label for="title" class="font-weight-bold">Site Article Per Page</label>
                <input type="number" class="form-control" name="siteArticlePerPage" value="{{Config::get('websettings.siteArticlePerPage')}}">
            </div>

            <div class="form-group col-sm-8">
                <label for="title" class="font-weight-bold">Site Book Per Page</label>
                <input type="number" class="form-control" name="siteBookPerPage" value="{{Config::get('websettings.siteBookPerPage')}}">
            </div>

            <div class="form-group col-sm-8">
                <label for="title" class="font-weight-bold">Site Comment Per Page</label>
                <input type="number" class="form-control" name="siteCommentPerPage" value="{{Config::get('websettings.siteCommentPerPage')}}">
            </div>

            <div class="form-group col-sm-8">
                <label for="title" class="font-weight-bold">Admin Item Per Page</label>
                <input type="number" class="form-control" name="adminItemPerPage" value="{{Config::get('websettings.adminItemPerPage')}}">
            </div>

            <div class="form-group col-sm-8">
                <label for="image" class="font-weight-bold">Site Logo</label>
                <img src="{{asset(Config::get('websettings.siteLogo'))}}" class="img-thumbnail img-responsive d-block">
                <input type="file" class="form-control-file" name="image">
            </div>

            <div class="form-group col-sm-8">
                <a href="{{route('admin.websetting.index')}}" class="btn btn-primary btn-danger">BACK</a> <input class="btn btn-primary" type="submit" value="EDIT">
            </div>
            <br>

        </form>
    </div>

@endsection


@push('script')

@endpush

resources/views/admin/main/systemSetting.blade.php
@extends('layouts.admin.app')

@section('title','Extra Settings.')

@push('css')


@endpush


@section('content')

    <div class="bg-white">
        <form method="post" action="{{route('admin.systemSetting.store')}}" enctype="multipart/form-data">
            @csrf
            @method('POST')


            <div class="form-group col-sm-8">
                <label for="title" class="font-weight-bold">Footer About US</label>
                <textarea name="footerAboutUs" class="form-control">{{Config::get('system.setting.footeraboutus')}}</textarea>
            </div>


            <div class="form-group col-sm-8">
                <label for="title" class="font-weight-bold">Footer Useful Links</label>
                <textarea name="footerUsefulLinks" class="form-control">{{Config::get('system.setting.footerusefullinks')}}</textarea>
            </div>


            <div class="form-group col-sm-8">
                <label for="title" class="font-weight-bold">Footer Social Links</label>
                <textarea name="footerSocialLinks" class="form-control">{{Config::get('system.setting.footersociallinks')}}</textarea>
            </div>

            <div class="form-group col-sm-8">
                <label for="title" class="font-weight-bold">About US</label>
                <textarea name="aboutUs" class="form-control">{{Config::get('system.setting.aboutus')}}</textarea>
            </div>

            <div class="form-group col-sm-8">
                <label for="title" class="font-weight-bold">Privacy</label>
                <textarea name="privacy" class="form-control">{{Config::get('system.setting.privacy')}}</textarea>
            </div>


            <div class="form-group col-sm-8">
                <a href="{{route('admin.websetting.index')}}" class="btn btn-primary btn-danger">BACK</a> <input class="btn btn-primary" type="submit" value="EDIT">
            </div>
            <br>

        </form>
    </div>

@endsection


@push('script')

@endpush